-- +goose Up
SELECT 'up SQL query';

CREATE TABLE IF NOT EXISTS links (
    id BIGSERIAL PRIMARY KEY,
    original TEXT NOT NULL UNIQUE,
    short VARCHAR(10) NOT NULL UNIQUE,
    clicks BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- +goose Down
SELECT 'down SQL query';

DROP TABLE IF EXISTS links;